
db.driver=com.mysql.cj.jdbc.Driver

# JDBC connection URL (includes time zone)
db.url=jdbc:mysql://localhost:3306/BD_NAME?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

# user with select, delete, upgrade and insert permissions
db.user=USER
db.password=PASSWORD

#[OPTIONAL] POOL CONFIGURATION
# Minimum number of inactive connections in the pool
db.minIdle=5

# Maximum number of inactive connections
db.maxIdle=20

# Maximum total number of connections (active + inactive)
db.maxTotal=50

# Maximum waiting time (ms) to obtain connection
# -1 = infinite wait (NOT recommended)
db.maxWaitMillis=3000
